In [64]:
from pandapower.create import (
    create_empty_network,
    create_bus,
    create_gen,
    create_load,
    create_line_from_parameters,
    create_transformer_from_parameters,
    create_ext_grid
)

from pandapower.run import runpp

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [65]:
#create empty network
net = create_empty_network()

In [66]:
#create buses
buses = {}

buses[1] = create_bus(net, vn_kv=16.5, name="Bus 1", type="b", in_service=True, max_vm_pu=1.05, min_vm_pu=0.90)
buses[2] = create_bus(net, vn_kv=18, name="Bus 2", type="b", in_service=True, max_vm_pu=1.05, min_vm_pu=0.90)
buses[3] = create_bus(net, vn_kv=13.8, name="Bus 3", type="b", in_service=True, max_vm_pu=1.05, min_vm_pu=0.90)

#create buses automatically
for i in range(4,10):
    buses[i] = create_bus(net, vn_kv=230, name=f"Bus {i}", index=i, type="b", in_service=True, max_vm_pu=1.05, min_vm_pu=0.90)

#data structure of the bus
net.bus

    name  vn_kv type  zone  in_service   geo  min_vm_pu  max_vm_pu
0  Bus 1   16.5    b  None        True  None        0.9       1.05
1  Bus 2   18.0    b  None        True  None        0.9       1.05
2  Bus 3   13.8    b  None        True  None        0.9       1.05
4  Bus 4  230.0    b  None        True  None        0.9       1.05
5  Bus 5  230.0    b  None        True  None        0.9       1.05
6  Bus 6  230.0    b  None        True  None        0.9       1.05
7  Bus 7  230.0    b  None        True  None        0.9       1.05
8  Bus 8  230.0    b  None        True  None        0.9       1.05
9  Bus 9  230.0    b  None        True  None        0.9       1.05

In [67]:
#create external grid
grids = {}

grids[1] = create_ext_grid(net, bus=buses[1], vm_pu=1.04, va_degree=0, max_p_mw=247.5, min_p_mw=0, max_q_mvar=247.5, min_q_mvar=-247.5, in_service=True, slack_weight=1/3, controllable=True)
grids[2] = create_ext_grid(net, bus=buses[2], vm_pu=1.025, va_degree=9.3057, max_p_mw=163.2, min_p_mw=0, max_q_mvar=192, min_q_mvar=-192, in_service=True, slack_weight=1/3, controllable=True)
grids[3] = create_ext_grid(net, bus=buses[3], vm_pu=1.025, va_degree=5.1420, max_p_mw=108.8, min_p_mw=0, max_q_mvar=128, min_q_mvar=-128, in_service=True, slack_weight=1/3, controllable=True)

#data structure of external grid
net.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,controllable,min_p_mw,max_p_mw,min_q_mvar,max_q_mvar
0,None,0,1.040,0.0000,0.333333,True,True,0.0,247.5,-247.5,247.5
1,None,1,1.025,9.3057,0.333333,True,True,0.0,163.2,-192.0,192.0
2,None,2,1.025,5.1420,0.333333,True,True,0.0,108.8,-128.0,128.0

In [68]:
#create generator
#gens = {}

#gens[1] = create_gen(net, bus=buses[1], vm_pu=1.04, p_mw=71.63, sn_mva=125, name="Gen 1", slack=True, controllable=True, in_service=True, max_p_mw=100, min_p_mw=20, max_q_mvar=75, min_q_mvar=-75)
#gens[2] = create_gen(net, bus=buses[2], vm_pu=1.025, p_mw=163, sn_mva=250, name="Gen 2", controllable=True, in_service=True, max_p_mw=200, min_p_mw=40, max_q_mvar=150, min_q_mvar=-150)
#gens[3] = create_gen(net, bus=buses[3], vm_pu=1.025, p_mw=85, sn_mva=125, name="Gen 3", controllable=True, in_service=True, max_p_mw=100, min_p_mw=20, max_q_mvar=75, min_q_mvar=-75)

#data structure of generator
#net.gen

In [69]:
#create transformer
trafos = {}
trafos[1] = create_transformer_from_parameters(net, hv_bus=buses[4], lv_bus=buses[1], sn_mva=250, vn_hv_kv=230, vn_lv_kv=16.5, vkr_percent=0.144, vk_percent=14.4, pfe_kw=0, i0_percent=0, vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 1", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100)
trafos[2] = create_transformer_from_parameters(net, hv_bus=buses[7], lv_bus=buses[2], sn_mva=200, vn_hv_kv=230, vn_lv_kv=18.0, vkr_percent=0.125, vk_percent=12.5, pfe_kw=0, i0_percent=0,vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 2", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100)
trafos[3] = create_transformer_from_parameters(net, hv_bus=buses[9], lv_bus=buses[3], sn_mva=150, vn_hv_kv=230, vn_lv_kv=13.8, vkr_percent=0.0879, vk_percent=8.79, pfe_kw=0, i0_percent=0,vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 3", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100)

#data structure of trafo
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_changer_type,id_characteristic_table,tap_dependency_table,parallel,df,in_service,vk0_percent,vector_group,max_loading_percent,oltc
0,Trafo 1,None,4,0,250.0,230.0,16.5,14.40,0.1440,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,YNd,100.0,False
1,Trafo 2,None,7,1,200.0,230.0,18.0,12.50,0.1250,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,YNd,100.0,False
2,Trafo 3,None,9,2,150.0,230.0,13.8,8.79,0.0879,0.0,...,NaN,<NA>,False,1,1.0,True,3.0,YNd,100.0,False

In [70]:
#create power lines
lines = {}
lines[1] = create_line_from_parameters(net, from_bus=buses[4], to_bus=buses[5], length_km=1, r_ohm_per_km=5.29, x_ohm_per_km=44.965, c_nf_per_km=1059.017 ,max_i_ka=1, name="Line4-5", in_service=True, type='ol', max_loading_percent=100)
lines[2] = create_line_from_parameters(net, from_bus=buses[4], to_bus=buses[6], length_km=1, r_ohm_per_km=8.993, x_ohm_per_km=48.668, c_nf_per_km=950.760 ,max_i_ka=1, name="Line4-6", in_service=True, type='ol', max_loading_percent=100)
lines[3] = create_line_from_parameters(net, from_bus=buses[5], to_bus=buses[7], length_km=1, r_ohm_per_km=16.928, x_ohm_per_km=85.169, c_nf_per_km=1841.264 ,max_i_ka=1, name="Line5-7", in_service=True, type='ol', max_loading_percent=100)
lines[4] = create_line_from_parameters(net, from_bus=buses[6], to_bus=buses[9], length_km=1, r_ohm_per_km=20.631, x_ohm_per_km=89.93, c_nf_per_km=2154.162 ,max_i_ka=1, name="Line6-9", in_service=True, type='ol', max_loading_percent=100)
lines[5] = create_line_from_parameters(net, from_bus=buses[7], to_bus=buses[8], length_km=1, r_ohm_per_km=4.4965, x_ohm_per_km=38.088, c_nf_per_km=896.552 ,max_i_ka=1, name="Line7-8", in_service=True, type='ol', max_loading_percent=100)
lines[6] = create_line_from_parameters(net, from_bus=buses[8], to_bus=buses[9], length_km=1, r_ohm_per_km=6.2951, x_ohm_per_km=53.3232, c_nf_per_km=1257.579 ,max_i_ka=1, name="Line8-9", in_service=True, type='ol', max_loading_percent=100)

#data structure of lines
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service,geo,max_loading_percent
0,Line4-5,None,4,5,1.0,5.2900,44.9650,1059.017,0.0,1.0,1.0,1,ol,True,None,100.0
1,Line4-6,None,4,6,1.0,8.9930,48.6680,950.760,0.0,1.0,1.0,1,ol,True,None,100.0
2,Line5-7,None,5,7,1.0,16.9280,85.1690,1841.264,0.0,1.0,1.0,1,ol,True,None,100.0
3,Line6-9,None,6,9,1.0,20.6310,89.9300,2154.162,0.0,1.0,1.0,1,ol,True,None,100.0
4,Line7-8,None,7,8,1.0,4.4965,38.0880,896.552,0.0,1.0,1.0,1,ol,True,None,100.0
5,Line8-9,None,8,9,1.0,6.2951,53.3232,1257.579,0.0,1.0,1.0,1,ol,True,None,100.0

In [71]:
#create load
loads = {}
loads[1] = create_load(net, name="Load Bus 4", bus=buses[4], p_mw=0, q_mvar=0, in_service=True, type='wye')
loads[2] = create_load(net, name="Load Bus 5", bus=buses[5], p_mw=125, q_mvar=50, in_service=True, type='wye')
loads[3] = create_load(net, name="Load Bus 6", bus=buses[6], p_mw=90, q_mvar=30, in_service=True, type='wye')
loads[4] = create_load(net, name="Load Bus 7", bus=buses[7], p_mw=0, q_mvar=0, in_service=True, type='wye')
loads[5] = create_load(net, name="Load Bus 8", bus=buses[8], p_mw=100, q_mvar=35, in_service=True, type='wye')
loads[6] = create_load(net, name="Load Bus 9", bus=buses[9], p_mw=0, q_mvar=0, in_service=True, type='wye')

#data structure for load
net.load

,name,bus,p_mw,q_mvar,const_z_p_percent,const_i_p_percent,const_z_q_percent,const_i_q_percent,sn_mva,scaling,in_service,type
0,Load Bus 4,4,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye
1,Load Bus 5,5,125.0,50.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye
2,Load Bus 6,6,90.0,30.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye
3,Load Bus 7,7,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye
4,Load Bus 8,8,100.0,35.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye
5,Load Bus 9,9,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,wye

In [72]:
#run load flow
runpp(net)

In [73]:
#display generator loading
net.res_gen

Empty DataFrame
Columns: [p_mw, q_mvar, va_degree, vm_pu]
Index: []

In [74]:
#display external grid loading
net.res_ext_grid

         p_mw     q_mvar
0   69.776038  27.484981
1  160.802305   6.202854
2   89.356215 -10.575968

In [75]:
#display trafo loading
net.res_trafo

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
0,-69.746087,-24.490037,69.776038,27.484981,0.029951,2.994944,0.181011,2.523187,1.025115,147.848151,1.040,0.0000,28.843896
1,-160.648255,9.201407,160.802305,6.202854,0.154050,15.404261,0.394097,5.035680,1.024934,153.818511,1.025,9.3057,78.498486
2,-89.311056,15.091608,89.356215,-10.575968,0.045159,4.515640,0.220360,3.672671,1.031803,152.300850,1.025,5.1420,58.523519

In [76]:
#display line loading
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,40.784272,23.045027,-40.526753,-38.812808,0.257519,-15.767780,0.114710,0.141592,0.141592,1.025115,147.848151,0.994833,146.081645,14.159161
1,28.961815,1.445010,-28.810753,-17.018489,0.151062,-15.573479,0.071008,0.083012,0.083012,1.025115,147.848151,1.011858,146.467762,8.301196
2,-84.473247,-11.187192,86.785520,-8.393988,2.312273,-19.581180,0.215009,0.213543,0.215009,0.994833,146.081645,1.024934,153.818511,21.500874
3,-61.189247,-12.981511,62.626317,-18.138112,1.437070,-31.119623,0.155177,0.158622,0.158622,1.011858,146.467762,1.031803,152.300850,15.862165
4,73.862735,-0.807419,-73.417303,-10.923299,0.445432,-11.730718,0.180912,0.183537,0.183537,1.024934,153.818511,1.015175,150.921640,18.353690
5,-26.582697,-24.076701,26.684739,3.046503,0.102042,-21.030198,0.088684,0.065342,0.088684,1.015175,150.921640,1.031803,152.300850,8.868420

In [77]:
#display bus voltage
net.res_bus

      vm_pu   va_degree        p_mw     q_mvar
0  1.040000    0.000000  -69.776038 -27.484981
1  1.025000    9.305700 -160.802305  -6.202854
2  1.025000    5.142000  -89.356215  10.575968
4  1.025115  147.848151    0.000000   0.000000
5  0.994833  146.081645  125.000000  50.000000
6  1.011858  146.467762   90.000000  30.000000
7  1.024934  153.818511    0.000000   0.000000
8  1.015175  150.921640  100.000000  35.000000
9  1.031803  152.300850    0.000000   0.000000

In [78]:
from pandapower import to_pickle
to_pickle(net, "ieee9bus.p")