In [46]:
from pandapower.create import (
    create_empty_network,
    create_bus,
    create_gen,
    create_load,
    create_line_from_parameters,
    create_transformer_from_parameters,
    create_ext_grid
)

from pandapower.run import runpp

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [47]:
#create empty network
net = create_empty_network()

In [48]:
#create buses
buses = {}

buses[1] = create_bus(net, vn_kv=16.5, name="Bus 1", type="b", in_service=True, max_vm_pu=1.1, min_vm_pu=0.90, zone="", geo="")
buses[2] = create_bus(net, vn_kv=18, name="Bus 2", type="b", in_service=True, max_vm_pu=1.1, min_vm_pu=0.90, zone="", geo="")
buses[3] = create_bus(net, vn_kv=13.8, name="Bus 3", type="b", in_service=True, max_vm_pu=1.1, min_vm_pu=0.90, zone="", geo="")

#create buses automatically
for i in range(4,10):
    buses[i] = create_bus(net, vn_kv=230, name=f"Bus {i}", index=i, type="b", in_service=True, max_vm_pu=1.1, min_vm_pu=0.90, zone="", geo="")

#data structure of the bus
net.bus

    name  vn_kv type zone  in_service geo  min_vm_pu  max_vm_pu
0  Bus 1   16.5    b             True            0.9        1.1
1  Bus 2   18.0    b             True            0.9        1.1
2  Bus 3   13.8    b             True            0.9        1.1
4  Bus 4  230.0    b             True            0.9        1.1
5  Bus 5  230.0    b             True            0.9        1.1
6  Bus 6  230.0    b             True            0.9        1.1
7  Bus 7  230.0    b             True            0.9        1.1
8  Bus 8  230.0    b             True            0.9        1.1
9  Bus 9  230.0    b             True            0.9        1.1

In [49]:
#create external grid
grids = {}

grids[1] = create_ext_grid(net, name="grid", bus=buses[1], vm_pu=1.04, va_degree=0, max_p_mw=247.5, min_p_mw=0, max_q_mvar=247.5, min_q_mvar=-247.5, in_service=True, slack_weight=1/3, controllable=True)
#grids[2] = create_ext_grid(net, bus=buses[2], vm_pu=1.025, va_degree=9.3057, max_p_mw=163.2, min_p_mw=0, max_q_mvar=192, min_q_mvar=-192, in_service=True, slack_weight=1/3, controllable=True)
#grids[3] = create_ext_grid(net, bus=buses[3], vm_pu=1.025, va_degree=5.1420, max_p_mw=108.8, min_p_mw=0, max_q_mvar=128, min_q_mvar=-128, in_service=True, slack_weight=1/3, controllable=True)

#data structure of external grid
net.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,controllable,min_p_mw,max_p_mw,min_q_mvar,max_q_mvar
0,grid,0,1.04,0.0,0.333333,True,True,0.0,247.5,-247.5,247.5

In [50]:
#create generator
gens = {}

#gens[1] = create_gen(net, bus=buses[1], vm_pu=1.04, p_mw=71.63, sn_mva=247.5, name="Gen 1", slack=True, controllable=False, in_service=True, max_p_mw=247.5, min_p_mw=0, max_q_mvar=247.5, min_q_mvar=-247.5)
gens[1] = create_gen(net, bus=buses[2], vm_pu=1.025, p_mw=163, sn_mva=192, name="Gen 2", controllable=True, in_service=True, max_p_mw=163.2, min_p_mw=0, max_q_mvar=192, min_q_mvar=-192, id_q_capability_characteristic=0.0, curve_style="", type="")
gens[2] = create_gen(net, bus=buses[3], vm_pu=1.025, p_mw=85, sn_mva=128, name="Gen 3", controllable=True, in_service=True, max_p_mw=108.8, min_p_mw=0, max_q_mvar=128, min_q_mvar=-128, id_q_capability_characteristic=0.0, curve_style="", type="")

#data structure of generator
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,controllable,id_q_capability_characteristic,reactive_capability_curve,curve_style,in_service,slack_weight,type,min_p_mw,max_p_mw
0,Gen 2,1,163.0,1.025,192.0,-192.0,192.0,1.0,False,True,0,False,,True,0.0,,0.0,163.2
1,Gen 3,2,85.0,1.025,128.0,-128.0,128.0,1.0,False,True,0,False,,True,0.0,,0.0,108.8

In [51]:
#create transformer
trafos = {}
trafos[1] = create_transformer_from_parameters(net, hv_bus=buses[4], lv_bus=buses[1], sn_mva=250, vn_hv_kv=230, vn_lv_kv=16.5, vkr_percent=0.144, vk_percent=14.4, pfe_kw=0, i0_percent=0, vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 1", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100, tap_step_degree=0.0, tap_changer_type="", id_characteristic_table=0.0, std_type="")
trafos[2] = create_transformer_from_parameters(net, hv_bus=buses[7], lv_bus=buses[2], sn_mva=200, vn_hv_kv=230, vn_lv_kv=18.0, vkr_percent=0.125, vk_percent=12.5, pfe_kw=0, i0_percent=0,vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 2", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100, tap_step_degree=0.0, tap_changer_type="", id_characteristic_table=0.0, std_type="")
trafos[3] = create_transformer_from_parameters(net, hv_bus=buses[9], lv_bus=buses[3], sn_mva=150, vn_hv_kv=230, vn_lv_kv=13.8, vkr_percent=0.0879, vk_percent=8.79, pfe_kw=0, i0_percent=0,vector_group='YNd', vk0_percent=3, in_service=True, name="Trafo 3", shift_degree=150, tap_side="hv", tap_neutral=0, tap_max=2, tap_min=-2, tap_step_percent=2.5, max_loading_percent=100, tap_step_degree=0.0, tap_changer_type="", id_characteristic_table=0.0, std_type="")

#data structure of trafo
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_changer_type,id_characteristic_table,tap_dependency_table,parallel,df,in_service,vk0_percent,vector_group,max_loading_percent,oltc
0,Trafo 1,,4,0,250.0,230.0,16.5,14.40,0.1440,0.0,...,,0,False,1,1.0,True,3.0,YNd,100.0,False
1,Trafo 2,,7,1,200.0,230.0,18.0,12.50,0.1250,0.0,...,,0,False,1,1.0,True,3.0,YNd,100.0,False
2,Trafo 3,,9,2,150.0,230.0,13.8,8.79,0.0879,0.0,...,,0,False,1,1.0,True,3.0,YNd,100.0,False

In [52]:
#create power lines
lines = {}
lines[1] = create_line_from_parameters(net, from_bus=buses[4], to_bus=buses[5], length_km=1, r_ohm_per_km=5.29, x_ohm_per_km=44.965, c_nf_per_km=1059.017 ,max_i_ka=1, name="Line4-5", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")
lines[2] = create_line_from_parameters(net, from_bus=buses[4], to_bus=buses[6], length_km=1, r_ohm_per_km=8.993, x_ohm_per_km=48.668, c_nf_per_km=950.760 ,max_i_ka=1, name="Line4-6", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")
lines[3] = create_line_from_parameters(net, from_bus=buses[5], to_bus=buses[7], length_km=1, r_ohm_per_km=16.928, x_ohm_per_km=85.169, c_nf_per_km=1841.264 ,max_i_ka=1, name="Line5-7", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")
lines[4] = create_line_from_parameters(net, from_bus=buses[6], to_bus=buses[9], length_km=1, r_ohm_per_km=20.631, x_ohm_per_km=89.93, c_nf_per_km=2154.162 ,max_i_ka=1, name="Line6-9", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")
lines[5] = create_line_from_parameters(net, from_bus=buses[7], to_bus=buses[8], length_km=1, r_ohm_per_km=4.4965, x_ohm_per_km=38.088, c_nf_per_km=896.552 ,max_i_ka=1, name="Line7-8", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")
lines[6] = create_line_from_parameters(net, from_bus=buses[8], to_bus=buses[9], length_km=1, r_ohm_per_km=6.2951, x_ohm_per_km=53.3232, c_nf_per_km=1257.579 ,max_i_ka=1, name="Line8-9", in_service=True, type='ol', max_loading_percent=100, std_type="", geo="")

#data structure of lines
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service,geo,max_loading_percent
0,Line4-5,,4,5,1.0,5.2900,44.9650,1059.017,0.0,1.0,1.0,1,ol,True,None,100.0
1,Line4-6,,4,6,1.0,8.9930,48.6680,950.760,0.0,1.0,1.0,1,ol,True,None,100.0
2,Line5-7,,5,7,1.0,16.9280,85.1690,1841.264,0.0,1.0,1.0,1,ol,True,None,100.0
3,Line6-9,,6,9,1.0,20.6310,89.9300,2154.162,0.0,1.0,1.0,1,ol,True,None,100.0
4,Line7-8,,7,8,1.0,4.4965,38.0880,896.552,0.0,1.0,1.0,1,ol,True,None,100.0
5,Line8-9,,8,9,1.0,6.2951,53.3232,1257.579,0.0,1.0,1.0,1,ol,True,None,100.0

In [53]:
#create load
loads = {}
loads[1] = create_load(net, name="Load Bus 4", bus=buses[4], p_mw=0, q_mvar=0, in_service=True, type='wye', controllable=False, sn_mva=0.0)
loads[2] = create_load(net, name="Load Bus 5", bus=buses[5], p_mw=125, q_mvar=50, in_service=True, type='wye', controllable=False, sn_mva=135)
loads[3] = create_load(net, name="Load Bus 6", bus=buses[6], p_mw=90, q_mvar=30, in_service=True, type='wye', controllable=False, sn_mva=95)
loads[4] = create_load(net, name="Load Bus 7", bus=buses[7], p_mw=0, q_mvar=0, in_service=True, type='wye', controllable=False, sn_mva=0)
loads[5] = create_load(net, name="Load Bus 8", bus=buses[8], p_mw=100, q_mvar=35, in_service=True, type='wye', controllable=False, sn_mva=106)
loads[6] = create_load(net, name="Load Bus 9", bus=buses[9], p_mw=0, q_mvar=0, in_service=True, type='wye', controllable=False, sn_mva=0)

#data structure for load
net.load

,name,bus,p_mw,q_mvar,const_z_p_percent,const_i_p_percent,const_z_q_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable
0,Load Bus 4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,wye,False
1,Load Bus 5,5,125.0,50.0,0.0,0.0,0.0,0.0,135.0,1.0,True,wye,False
2,Load Bus 6,6,90.0,30.0,0.0,0.0,0.0,0.0,95.0,1.0,True,wye,False
3,Load Bus 7,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,wye,False
4,Load Bus 8,8,100.0,35.0,0.0,0.0,0.0,0.0,106.0,1.0,True,wye,False
5,Load Bus 9,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,True,wye,False

In [54]:
#run load flow
runpp(net)

In [55]:
#display generator loading
net.res_gen

    p_mw     q_mvar  va_degree  vm_pu
0  163.0   6.441012   9.278184  1.025
1   85.0 -10.663835   4.664066  1.025

In [56]:
#display external grid loading
net.res_ext_grid

        p_mw     q_mvar
0  71.870928  27.273723

In [57]:
#display trafo loading
net.res_trafo

,p_hv_mw,q_hv_mvar,p_lv_mw,q_lv_mvar,pl_mw,ql_mvar,i_hv_ka,i_lv_ka,vm_hv_pu,va_hv_degree,vm_lv_pu,va_lv_degree,loading_percent
0,-71.839459,-24.126923,71.870928,27.273723,0.031470,3.146800,0.185543,2.586364,1.025264,147.783516,1.040,0.000000,29.566109
1,-162.841698,9.388349,163.000000,6.441012,0.158302,15.829361,0.399498,5.104690,1.024905,153.715662,1.025,9.278184,79.574249
2,-84.959067,14.756898,85.000000,-10.663835,0.040933,4.093062,0.209796,3.496604,1.031758,151.961220,1.025,4.664066,55.717928

In [58]:
#display line loading
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,41.059108,23.054900,-40.799447,-38.809338,0.259661,-15.754438,0.115291,0.142066,0.142066,1.025264,147.783516,0.994957,146.004431,14.206565
1,30.780351,1.072023,-30.612909,-16.562870,0.167442,-15.490847,0.075407,0.086328,0.086328,1.025264,147.783516,1.012082,146.307746,8.632838
2,-84.200553,-11.190662,86.497384,-8.471067,2.296831,-19.661729,0.214301,0.212865,0.214301,0.994957,146.004431,1.024905,153.715662,21.430116
3,-59.387091,-13.437130,60.739043,-18.059980,1.351952,-31.497110,0.151018,0.154169,0.154169,1.012082,146.307746,1.031758,151.961220,15.416924
4,76.344315,-0.917282,-75.868819,-10.557319,0.475496,-11.474601,0.186998,0.189421,0.189421,1.024905,153.715662,1.015108,150.719471,18.942055
5,-24.131181,-24.442681,24.220024,3.303082,0.088843,-21.139598,0.084937,0.059472,0.084937,1.015108,150.719471,1.031758,151.961220,8.493679

In [59]:
#display bus voltage
net.res_bus

      vm_pu   va_degree        p_mw     q_mvar
0  1.040000    0.000000  -71.870928 -27.273723
1  1.025000    9.278184 -163.000000  -6.441012
2  1.025000    4.664066  -85.000000  10.663835
4  1.025264  147.783516    0.000000   0.000000
5  0.994957  146.004431  125.000000  50.000000
6  1.012082  146.307746   90.000000  30.000000
7  1.024905  153.715662    0.000000   0.000000
8  1.015108  150.719471  100.000000  35.000000
9  1.031758  151.961220    0.000000   0.000000

In [60]:
from pandapower import to_pickle
to_pickle(net, "ieee9bus.p")

In [61]:
net.res_line["loading_percent"]

0    14.206565
1     8.632838
2    21.430116
3    15.416924
4    18.942055
5     8.493679
Name: loading_percent, dtype: float64